apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pscdth44m-go 
  janus-idp.io/tekton: pscdth44m-go
  backstage.io/kubernetes-id: pscdth44m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pscdth44m-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml